#!/bin/bash
# =============================================================================
# config/util_aliases.sh
# DevKit Container Shell Aliases & Shortcuts (ROS 1/2, Python uv, C++)
# =============================================================================

source "${WORKSPACE_PATH:-/workspace}/config/util_paths.sh" 2>/dev/null || true

export SYS_PYTHON_EXE=${SYS_PYTHON_EXE:-/usr/bin/python3}

# Shared CMake knobs (.env → compose → here): CMAKE_EXTRA_ARGS, the documented
# C/C++ standard pins and the OPENCV_CUDA policy. Fills DEVKIT_CMAKE_EXTRA.
__cmake_extra_args() {
    DEVKIT_CMAKE_EXTRA=()
    [ -n "${CMAKE_EXTRA_ARGS:-}" ] && read -r -a DEVKIT_CMAKE_EXTRA <<< "${CMAKE_EXTRA_ARGS}"
    [ -n "${CMAKE_C_STANDARD:-}" ] && DEVKIT_CMAKE_EXTRA+=("-DCMAKE_C_STANDARD=${CMAKE_C_STANDARD}")
    [ -n "${CMAKE_CXX_STANDARD:-}" ] && DEVKIT_CMAKE_EXTRA+=("-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}")
    # OPENCV_CUDA reaches the compiler here, not just `gpu opencv_args`: a project
    # that builds OpenCV from source needs the flags at configure time. Probed per
    # call on purpose — 90 ms against a build measured in seconds is not worth a
    # cache to invalidate.
    local gpu_args=()
    read -r -a gpu_args <<< "$(bash "${WS_SCRIPTS}/setup_gpu.sh" opencv_args 2>/dev/null || true)"
    DEVKIT_CMAKE_EXTRA+=("${gpu_args[@]}")
    return 0
}

# A missing build tool means the wrong image, not a broken workspace — say which.
__require_cmd() {
    command -v "$1" >/dev/null 2>&1 && return 0
    echo -e "  \033[31m[ERROR]\033[0m '$1' not found in this image." >&2
    echo -e "  \033[36m[Hint]\033[0m  ROS builds need ENV=ros; plain CMake projects use 'mbuild'." >&2
    return 1
}

# ${WS_ROOT}/.venv, colcon.meta and compile_commands.json are regenerated by the
# same script config/init_bash.sh runs at shell start; call it after anything
# that creates their targets so the links do not lag a whole session behind.
__refresh_links() {
    [ -x "${WS_SCRIPTS}/util_setup_links.sh" ] && "${WS_SCRIPTS}/util_setup_links.sh" --skip-compile-commands
    return 0
}

# The build flags the MOTD advertises: --debug/--release/--pkg/--meta, with
# everything else passed through untouched ('--' forces passthrough). $1 selects
# the generation, because the package selector differs per tool:
#   2 = colcon (--packages-select, --metas), 1 = catkin_make (--only-pkg-with-deps),
#   cmake = plain CMake, where neither applies.
# Fills DEVKIT_BUILD_TYPE_ARG / DEVKIT_BUILD_SELECT / DEVKIT_BUILD_PASSTHRU.
__parse_build_flags() {
    local gen="${1:-2}"; shift
    # RelWithDebInfo, not CMake's empty default: an unoptimised robotics build is
    # a performance bug nobody reads in the log.
    DEVKIT_BUILD_TYPE_ARG="RelWithDebInfo"
    DEVKIT_BUILD_SELECT=()
    DEVKIT_BUILD_PASSTHRU=()
    while [ $# -gt 0 ]; do
        case "$1" in
            --debug)   DEVKIT_BUILD_TYPE_ARG="Debug"; shift ;;
            --release) DEVKIT_BUILD_TYPE_ARG="Release"; shift ;;
            --pkg)
                shift
                if [ $# -eq 0 ] || [[ "$1" == --* ]]; then
                    echo -e "  \033[31m[ERROR]\033[0m --pkg requires at least one package name." >&2
                    return 2
                fi
                case "$gen" in
                    2) DEVKIT_BUILD_SELECT+=(--packages-select) ;;
                    1) DEVKIT_BUILD_SELECT+=(--only-pkg-with-deps) ;;
                    *) echo -e "  \033[31m[ERROR]\033[0m --pkg applies to ROS builds only." >&2; return 2 ;;
                esac
                while [ $# -gt 0 ] && [[ "$1" != --* ]]; do DEVKIT_BUILD_SELECT+=("$1"); shift; done ;;
            --meta)
                if [ "$gen" = "2" ]; then
                    DEVKIT_BUILD_SELECT+=(--metas "${WS_CONFIG:-${WS_ROOT}/config}/colcon.meta")
                else
                    echo -e "  \033[33m[WARN]\033[0m --meta is a colcon option; ignored here." >&2
                fi; shift ;;
            --) shift; DEVKIT_BUILD_PASSTHRU+=("$@"); break ;;
            *)  DEVKIT_BUILD_PASSTHRU+=("$1"); shift ;;
        esac
    done
}

# Parse --share flag; auto-enable for ROS 1 Noetic (tied to system Python ABI)
__parse_share_flag() {
    DEVKIT_SHARE_MODE=false
    DEVKIT_REMAINING_ARGS=()
    for arg in "$@"; do
        case "$arg" in
            --share) DEVKIT_SHARE_MODE=true ;;
            *) DEVKIT_REMAINING_ARGS+=("$arg") ;;
        esac
    done
    [ "${ROS_DISTRO:-}" = "noetic" ] && DEVKIT_SHARE_MODE=true
}

# --- General System & Help ----------------------------------------------------
alias h='__print_container_help'
alias help='__print_container_help'
# Functions, not aliases: aliases never expand in a non-interactive shell, and
# these three are exactly what CI and `make exec` want to run.
hwcheck()    { bash "${WS_SCRIPTS}/check_hardware.sh" "$@"; }
gpus()       { bash "${WS_SCRIPTS}/setup_gpu.sh" status "$@"; }
check_deps() { bash "${WS_SCRIPTS}/check_deps.sh" "$@"; }

# hw_check: pre-streamline spelling of `hwcheck`. A base kit must not break the
# scripts already calling it, so it forwards and points at the current name.
hw_check() {
    echo -e "  \033[33m[WARN]\033[0m 'hw_check' is deprecated — use 'hwcheck'." >&2
    bash "${WS_SCRIPTS}/check_hardware.sh" "$@"
}

__print_container_help() {
    # Same discipline as devkit_auto_color, but as locals: this runs in the
    # user's interactive shell, where `exec >` would redirect it permanently.
    local T='\033[38;2;45;212;191m' S='\033[0;36m' G='\033[32m' Y='\033[33m' C='\033[36m' P='\033[35m' N='\033[0m'
    if [ -n "${NO_COLOR:-}" ] || [ ! -t 1 ]; then T='' S='' G='' Y='' C='' P='' N=''; fi
    echo -e "\n  ${T}DevKit Container Shortcuts & Aliases${N}"

    echo -e "${S}[ Quick Start & Build ] =============================${N}"
    printf "  ${G}%-20s${N} : %s\n" "mksync [--share]" "Initialize workspace; --share for system-site-packages"
    printf "  ${G}%-20s${N} : %s\n" "cbuild / mbuild" "Build workspace (ROS colcon or Modern CMake)"
    printf "  ${G}%-20s${N} : %s\n" "cbt / cbtr" "Run tests / view test results"
    printf "  ${G}%-20s${N} : %s\n" "s / sb" "Source workspace / Source .bashrc"
    printf "  ${G}%-20s${N} : %s\n" "mclean" "Clean build, install & log output directories"

    echo -e "\n${S}[ ROS Subsystem ] ===================================${N}"
    printf "  ${G}%-20s${N} : %s\n" "rt / rte / rth" "Topic list / echo / hz"
    printf "  ${G}%-20s${N} : %s\n" "rn / rs / rp" "Node list / service list / param list"
    printf "  ${G}%-20s${N} : %s\n" "rr / rl / ri" "ros2 run / launch / interface show"

    echo -e "\n${S}[ Python & Environment ] ============================${N}"
    printf "  ${Y}%-20s${N} : %s\n" "mkenv / activate" "Create or activate Python virtualenv (.venv)"
    printf "  ${Y}%-20s${N} : %s\n" "uvs / uvr / uvp / uvl" "uv sync / run / pip install / pip list"
    printf "  ${Y}%-20s${N} : %s\n" "uvpython / syspython" "Run Python in venv or system environment"
    printf "  ${Y}%-20s${N} : %s\n" "pyv" "Show which python/venv/uv is active"
    printf "  ${Y}%-20s${N} : %s\n" "sync_deps" "Sync external dependencies from .repos file"

    echo -e "\n${S}[ Navigation & Utilities ] ==========================${N}"
    printf "  ${C}%-20s${N} : %s\n" "cw / cs / cc" "cd to workspace root / src / config"
    printf "  ${C}%-20s${N} : %s\n" "ll / la / g" "ls -alF / ls -A / git wrapper"
    printf "  ${C}%-20s${N} : %s\n" "k / k9" "killall / killall -9"
    printf "  ${C}%-20s${N} : %s\n" "ccs / ccc" "ccache stats / clear ccache"

    echo -e "\n${S}[ Hardware & Diagnostics ] ==========================${N}"
    printf "  ${P}%-20s${N} : %s\n" "hwcheck" "6-section scan: system, network, GPU, display, identity, toolchain"
    printf "  ${P}%-20s${N} : %s\n" "gpus" "Full render stack: GL/GLX, EGL, Vulkan, D3D12, loader paths"
    printf "  ${P}%-20s${N} : %s\n" "gpu <mode>" "Switch GPU mode (auto/nvidia/tegra/intel/amd/igpu/cpu)"
    printf "  ${P}%-20s${N} : %s\n" "gpu_check / vulkan_check" "One-line OpenGL / Vulkan renderer check"
    printf "  ${P}%-20s${N} : %s\n" "gpu_test / pyt" "Render a real frame / check the ML stack sees the GPU"
    printf "  ${P}%-20s${N} : %s\n\n" "check_deps" "Check missing shared libraries in install/"
}

# --- ROS 1 / ROS 2 Environment & Build --------------------------------------
__smart_source() {
    if [ -f "${WS_ROOT}/install/setup.bash" ]; then
        source "${WS_ROOT}/install/setup.bash"
        echo -e "  \033[32m[OK]\033[0m Sourced ${WS_ROOT}/install/setup.bash"
    elif [ -f "/opt/ros/${ROS_DISTRO:-humble}/setup.bash" ]; then
        source "/opt/ros/${ROS_DISTRO:-humble}/setup.bash"
        echo -e "  \033[32m[OK]\033[0m Sourced /opt/ros/${ROS_DISTRO:-humble}/setup.bash"
    else
        echo -e "  \033[31m[ERROR]\033[0m No ROS setup.bash found!"
    fi
}

alias s='__smart_source'
alias sb='source ~/.bashrc'

# cbuild must be a FUNCTION, not an alias: mksync() calls it, and aliases are
# not expanded inside functions in non-interactive shells (docker build runs
# `bash -lc "... mksync"`). Keep every build entry point callable from scripts.
#
# --symlink-install is a DEVELOPMENT-only optimisation: it symlinks launch files,
# Python modules and resources from src/ into install/ so edits take effect
# without rebuilding. Production images copy only install/ (never src/), so those
# symlinks would dangle in the shipped artifact — DEVKIT_BUILD_TYPE=prod forces a
# real copy. COLCON_EXTRA_FLAGS (already plumbed through compose) is honoured too.
if [ "${ROS_VERSION:-2}" = "2" ]; then
    cbuild() {
        __require_cmd colcon || return 1
        local link_flag=(--symlink-install) extra=()
        [ "${DEVKIT_BUILD_TYPE:-dev}" = "prod" ] && link_flag=()
        [ -n "${COLCON_EXTRA_FLAGS:-}" ] && read -r -a extra <<< "${COLCON_EXTRA_FLAGS}"
        __parse_build_flags 2 "$@" || return 2
        __cmake_extra_args
        # Run from WS_ROOT so build/, install/, log/ and the colcon.meta link
        # land at the workspace root regardless of the caller's cwd.
        ( cd "${WS_ROOT}" && colcon build "${link_flag[@]}" "${extra[@]}" "${DEVKIT_BUILD_SELECT[@]}" \
            --cmake-args -Wno-dev --no-warn-unused-cli \
            -DCMAKE_BUILD_TYPE="${DEVKIT_BUILD_TYPE_ARG}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            "${DEVKIT_CMAKE_EXTRA[@]}" "${DEVKIT_BUILD_PASSTHRU[@]}" ) || return 1
        __refresh_links
    }
    alias cbt='colcon test'
    alias cbtr='colcon test-result --all'
    alias rt='ros2 topic list'
    alias rte='ros2 topic echo'
    alias rth='ros2 topic hz'
    alias rn='ros2 node list'
    alias rs='ros2 service list'
    alias rp='ros2 param list'
    alias rr='ros2 run'
    alias rl='ros2 launch'
    alias ri='ros2 interface show'
else
    # catkin_make populates devel/ and build/, never install/. The production
    # runtime image copies install/ only, so a prod build must run the install
    # target explicitly or the shipped image contains no ROS artifacts at all.
    cbuild() {
        __require_cmd catkin_make || return 1
        local extra=()
        [ -n "${COLCON_EXTRA_FLAGS:-}" ] && read -r -a extra <<< "${COLCON_EXTRA_FLAGS}"
        __parse_build_flags 1 "$@" || return 2
        __cmake_extra_args
        set -- "${DEVKIT_BUILD_PASSTHRU[@]}"
        DEVKIT_CMAKE_EXTRA+=("-DCMAKE_BUILD_TYPE=${DEVKIT_BUILD_TYPE_ARG}")
        if [ "${DEVKIT_BUILD_TYPE:-dev}" = "prod" ]; then
            ( cd "${WS_ROOT}" && catkin_make install "${DEVKIT_BUILD_SELECT[@]}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                -DCMAKE_INSTALL_PREFIX="${WS_ROOT}/install" "${DEVKIT_CMAKE_EXTRA[@]}" "${extra[@]}" "$@" ) || return 1
            if [ -z "$(find "${WS_ROOT}/install" -mindepth 2 -type f -print -quit 2>/dev/null)" ]; then
                echo -e "  \033[31m[ERROR]\033[0m Production build installed no artifacts into ${WS_ROOT}/install."
                echo -e "  \033[36m[Hint]\033[0m  Add install() rules to your catkin CMakeLists.txt;"
                echo -e "  \033[36m[Hint]\033[0m  the production runtime image copies install/ only."
                return 1
            fi
        else
            ( cd "${WS_ROOT}" && catkin_make "${DEVKIT_BUILD_SELECT[@]}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                "${DEVKIT_CMAKE_EXTRA[@]}" "${extra[@]}" "$@" ) || return 1
        fi
        __refresh_links
    }
    alias cbt='catkin_make run_tests'
    alias cbtr='catkin_test_results'
    alias rt='rostopic list'
    alias rte='rostopic echo'
    alias rth='rostopic hz'
    alias rn='rosnode list'
    alias rs='rosservice list'
    alias rp='rosparam list'
    alias rr='rosrun'
    alias rl='roslaunch'
    alias ri='rosmsg show'
fi

# --- Python & Virtualenv (uv) ------------------------------------------------
uvr() { uv run "$@"; }
uvp() { uv pip install "$@"; }
uvl() { uv pip list; }

# uv sync: respects UV_SYNC_FLAGS env var and UV_EXTRA for optional dependency
# groups. A function, not an alias: mksync() calls it non-interactively.
uvs() {
    local venv="${WS_VENV:-${WS_ROOT}/install/.venv}"
    local pyproject="${WS_SRC:-${WS_ROOT}/src}/pyproject.toml"
    local req_file="${WS_ROOT}/dependencies/requirements.txt"
    local sync_flags=()
    [ -n "${UV_SYNC_FLAGS:-}" ] && read -r -a sync_flags <<< "${UV_SYNC_FLAGS}"
    [ -x "${venv}/bin/python" ] || mkenv || return 1

    if [ -f "$pyproject" ]; then
        local extra_args=()
        if [ -n "${UV_EXTRA:-}" ]; then
            extra_args=(--extra "${UV_EXTRA}")
        fi
        # --python pins uv to the interpreter the venv already has. Without it uv
        # compares against UV_PYTHON (3.10 from the image) and REPLACES the venv
        # when they differ — which silently turns the shared venv `mksync --share`
        # just built (noetic, system python) back into a pure one, losing rospy.
        # UV_PROJECT_ENVIRONMENT is not redundant with init_bash.sh either: during
        # `docker build` this runs before /etc/devkit/shell-env.sh exists, so the
        # export is absent and uv would create src/.venv next to pyproject.toml.
        UV_PROJECT_ENVIRONMENT="$venv" \
            uv sync --project "${WS_SRC:-${WS_ROOT}/src}" --python "${venv}/bin/python" \
                "${extra_args[@]}" "${sync_flags[@]}" "$@"
    elif [ -f "$req_file" ] && grep -qv '^[[:space:]]*#' "$req_file" 2>/dev/null; then
        uv pip install --python "${venv}/bin/python" -r "$req_file" "$@"
    else
        echo -e "  \033[34m[INFO]\033[0m No Python dependency manifest found. Skipping uv sync."
    fi
}

# Detect project type: ROS | CPP | PYTHON
# NOTE: `-print -quit` — `-quit` alone is an action, which suppresses find's
# implicit -print and always yields an empty string (silently disabling detection).
__detect_project_type() {
    local src="${WS_SRC:-${WS_ROOT}/src}"
    [ -d "$src" ] || { echo "PYTHON"; return; }
    if [ -n "${ROS_DISTRO:-}" ] && command -v colcon >/dev/null 2>&1; then
        if [ -f "${src}/CMakeLists.txt" ] || [ -n "$(find "$src" -maxdepth 3 -name "package.xml" -print -quit 2>/dev/null)" ]; then
            echo "ROS"; return
        fi
    fi
    if [ -n "$(find "$src" -maxdepth 3 -name "CMakeLists.txt" -print -quit 2>/dev/null)" ]; then
        echo "CPP"
    else
        echo "PYTHON"
    fi
}

# The venv is NAMED after the project (`(myproject-lee)`) instead of after its
# directory, so one glance tells which workspace a shell belongs to. Trailing
# arguments reach `uv venv`, so `mkenv --link-mode copy` works.
mkenv() {
    local venv_dir="${WS_VENV:-${WS_ROOT}/install/.venv}"
    local prompt="${COMPOSE_PROJECT_NAME:-.venv}"
    local share=() py="${UV_PYTHON:-3.10}" label="Pure"
    __parse_share_flag "$@"
    if [ "$DEVKIT_SHARE_MODE" = true ]; then
        share=(--system-site-packages); py="${SYS_PYTHON_EXE}"; label="Shared"
    fi
    if command -v uv >/dev/null 2>&1; then
        uv venv "$venv_dir" --python "$py" "${share[@]}" --seed \
            --prompt "$prompt" "${DEVKIT_REMAINING_ARGS[@]}" || return 1
    else
        # The fallback must honour --share too, or a noetic workspace (where it
        # is forced) silently ends up without rospy.
        python3 -m venv "${share[@]}" --prompt "$prompt" "$venv_dir" || return 1
    fi
    __refresh_links   # ${WS_ROOT}/.venv should point at the new environment now
    echo -e "  \033[32m[OK]\033[0m ${label} venv '${prompt}' created: ${venv_dir}"
    source "${venv_dir}/bin/activate"
}

activate() {
    local venv_dir="${WS_VENV:-${WS_ROOT}/install/.venv}"
    if [ -f "${venv_dir}/bin/activate" ]; then
        source "${venv_dir}/bin/activate"
        # Re-entrant with no help from us: both uv's and CPython's activate call
        # `deactivate nondestructive` first, restoring PATH before re-prefixing.
        # Same normalisation as config/init_bash.sh: one pair of parens either way.
        VIRTUAL_ENV_PROMPT="${VIRTUAL_ENV_PROMPT#\(}"; VIRTUAL_ENV_PROMPT="${VIRTUAL_ENV_PROMPT%\) }"
        echo -e "  \033[32m[OK]\033[0m Activated virtualenv: ${venv_dir}"
    else
        echo -e "  \033[33m[WARN]\033[0m Virtualenv not found at ${venv_dir}. Run 'mkenv' first."
    fi
}

alias sync_deps='bash ${WS_SCRIPTS}/setup_sync_deps.sh'

mksync() {
    __parse_share_flag "$@"
    local mkenv_args=()
    [ "$DEVKIT_SHARE_MODE" = true ] && mkenv_args=(--share)
    # Snapshot now: mkenv() re-runs __parse_share_flag and overwrites the globals.
    local uvs_args=("${DEVKIT_REMAINING_ARGS[@]}")

    # 1. venv → activate → Python packages → system/ROS dependencies
    mkenv "${mkenv_args[@]}" && \
    uvs "${uvs_args[@]}" && \
    bash "${WS_SCRIPTS}/setup_sync_deps.sh" --rosdep || return 1

    # 2. Build with whatever the project layout calls for
    local project_type
    project_type=$(__detect_project_type)
    case "$project_type" in
        "ROS")
            echo -e "  \033[34m[INFO]\033[0m ROS workspace detected — building..."
            cbuild && __smart_source ;;
        "CPP")
            echo -e "  \033[34m[INFO]\033[0m Pure C++ project detected — running mbuild..."
            mbuild ;;
        *)
            echo -e "  \033[32m[OK]\033[0m Pure Python project — no build step needed." ;;
    esac
}

# pyv: one-glance answer to "which python am I actually running?"
pyv() {
    printf '  %-11s: %s (%s)\n' "python3" "$(command -v python3)" "$(python3 -V 2>&1 | cut -d' ' -f2)"
    printf '  %-11s: %s\n' "venv" "${VIRTUAL_ENV:-inactive}"
    command -v uv >/dev/null 2>&1 && printf '  %-11s: %s\n' "uv" "$(uv --version 2>/dev/null | cut -d' ' -f2)"
    python3 -c 'import sys; print("  {:<11}: {}".format("sys.prefix", sys.prefix))' 2>/dev/null
}

uvpython() {
    local venv_py="${WS_VENV:-${WS_ROOT}/install/.venv}/bin/python3"
    if [ -f "$venv_py" ]; then
        "$venv_py" "$@"
    else
        python3 "$@"
    fi
}

syspython() {
    /usr/bin/python3 "$@"
}

# --- Navigation & Utilities --------------------------------------------------
alias cw='cd "${WS_ROOT}"'
alias cs='cd "${WS_SRC}"'
alias cc='cd "${WS_CONFIG}"'

alias ll='ls -alF'
alias la='ls -A'
alias g='git'
alias k='killall'
alias k9='killall -9'

alias ccs='ccache -s'
alias ccc='ccache -C'

# --- Hardware & GPU Diagnostics ---------------------------------------------
gpu() {
    local mode="${1:-status}"
    case "$mode" in
        status|opencv_args|auto|nvidia|tegra|intel|amd|igpu|cpu)
            source "${WS_SCRIPTS}/setup_gpu.sh" "$mode"
            ;;
        *)
            echo "Usage: gpu {status|opencv_args|auto|nvidia|tegra|intel|amd|igpu|cpu}"
            return 1
            ;;
    esac
}

alias gpu_check='glxinfo 2>&1 | grep -E "OpenGL (vendor|renderer|version)" || echo "No display / glxinfo unavailable"'
alias vulkan_check='vulkaninfo --summary 2>/dev/null | head -20 || echo "Vulkan not available"'

# gpu_test: actually RENDER something. `gpus`/`gpu_check` report what the stack
# claims; this proves frames are produced and at what rate — the difference
# between "configured" and "working". Vendor- and framework-agnostic.
gpu_test() {
    if ! command -v glxgears >/dev/null 2>&1; then
        echo -e "  \033[33m[WARN]\033[0m glxgears not installed (apt: mesa-utils)."; return 1
    fi
    if [ -z "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]; then
        echo -e "  \033[33m[WARN]\033[0m No DISPLAY/WAYLAND_DISPLAY — cannot render."; return 1
    fi
    echo -e "  \033[34m[INFO]\033[0m Rendering for 5s..."
    local out
    out="$(timeout 6 glxgears -info 2>&1 | grep -E "GL_RENDERER|frames in" | head -3 || true)"
    if [ -z "$out" ]; then
        echo -e "  \033[31m[ERROR]\033[0m No frames rendered — check 'gpus' and 'make xauth'."; return 1
    fi
    echo "$out" | sed 's/^/    /'
}

# torch_check / pyt: the first question after a GPU setup is whether the ML
# stack actually sees the device. Reports gracefully when torch is absent.
torch_check() {
    local py="${WS_VENV:-${WS_ROOT}/install/.venv}/bin/python3"
    [ -x "$py" ] || py=python3
    "$py" - <<'PY' 2>/dev/null || echo -e "  \033[33m[WARN]\033[0m PyTorch not installed (run: uvs, or set UV_EXTRA=gpu)."
import torch
print(f"    torch      {torch.__version__}")
print(f"    CUDA build {torch.version.cuda or 'cpu-only'}")
avail = torch.cuda.is_available()
print(f"    CUDA avail {avail}")
if avail:
    print(f"    device     {torch.cuda.get_device_name(0)}")
elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
    print("    device     Apple MPS")
PY
}
alias pyt='torch_check'

# --- Modern CMake & C++ Shortcuts --------------------------------------------
mbuild() {
    # Source root: repository root if it carries the top-level CMakeLists.txt,
    # otherwise src/ (the layout __detect_project_type reports as CPP).
    local src_dir="${WS_ROOT}"
    if [ ! -f "${WS_ROOT}/CMakeLists.txt" ]; then
        src_dir="${WS_SRC:-${WS_ROOT}/src}"
    fi
    if [ ! -f "${src_dir}/CMakeLists.txt" ]; then
        echo -e "  \033[31m[ERROR]\033[0m No CMakeLists.txt found in ${WS_ROOT} or ${src_dir}."
        return 1
    fi
    __require_cmd cmake || return 1
    __parse_build_flags cmake "$@" || return 2
    __cmake_extra_args
    cmake -B "${WS_ROOT}/build" -S "$src_dir" -Wno-dev --no-warn-unused-cli \
          -DCMAKE_BUILD_TYPE="${DEVKIT_BUILD_TYPE_ARG}" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_INSTALL_PREFIX="${WS_ROOT}/install" "${DEVKIT_CMAKE_EXTRA[@]}" "${DEVKIT_BUILD_PASSTHRU[@]}" \
        && cmake --build "${WS_ROOT}/build" -j"$(nproc 2>/dev/null || echo 4)" || return 1
    __refresh_links

    # Production images copy install/ and never build/, so a prod build MUST
    # install. Without this a C++ prod image ships no executable at all.
    if [ "${DEVKIT_BUILD_TYPE:-dev}" = "prod" ]; then
        cmake --install "${WS_ROOT}/build" || return 1
        if [ -z "$(find "${WS_ROOT}/install" -mindepth 2 -type f -print -quit 2>/dev/null)" ]; then
            echo -e "  \033[31m[ERROR]\033[0m Production build installed no artifacts into ${WS_ROOT}/install."
            echo -e "  \033[36m[Hint]\033[0m  Add install(TARGETS ... DESTINATION bin/lib) rules to your CMakeLists.txt;"
            echo -e "  \033[36m[Hint]\033[0m  the production runtime image copies install/ only."
            return 1
        fi
    fi
}

# ${WS_ROOT:?}: util_paths.sh is sourced with `|| true` above — if it failed,
# an unset WS_ROOT would make this rm -rf /build /log … instead of erroring.
# build/install/log are named-volume MOUNT POINTS in the dev container: rm -rf
# empties them but cannot remove the directory itself (EBUSY) — expected, so
# stderr is suppressed. The find afterwards distinguishes that benign case from
# real failures (permissions, root-owned files): leftover CONTENT means failure.
mclean() {
    local dirs=("${WS_ROOT:?}/build" "${WS_ROOT:?}/log" "${WS_ROOT:?}/install/bin" "${WS_ROOT:?}/install/lib")
    local what="build, log and install output directories (--all removes install/ too)"
    if [ "${1:-}" = "--all" ]; then
        dirs=("${WS_ROOT:?}/build" "${WS_ROOT:?}/log" "${WS_ROOT:?}/devel" "${WS_ROOT:?}/install")
        what="ALL build output including install/ and the virtualenv (re-run mksync)"
    fi
    rm -rf "${dirs[@]}" 2>/dev/null || true
    if [ -n "$(find "${dirs[@]}" -mindepth 1 -print -quit 2>/dev/null)" ]; then
        echo -e "  \033[31m[ERROR]\033[0m Some entries could not be removed (root-owned? permissions?)."
        echo -e "  \033[36m[Hint]\033[0m  Inspect with: ls -la ${WS_ROOT:?}/build ${WS_ROOT:?}/install"
        return 1
    fi
    echo -e "  \033[32m[OK]\033[0m Emptied ${what}."
}

# --- Tab Completions ---------------------------------------------------------
complete -W "status opencv_args auto nvidia tegra intel amd igpu cpu" gpu 2>/dev/null || true
complete -W "--packages-select --packages-up-to --cmake-args --event-handlers" cbuild 2>/dev/null || true
complete -W "-DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Debug" mbuild 2>/dev/null || true
complete -W "--rosdep --force" sync_deps 2>/dev/null || true
complete -W "--all" mclean 2>/dev/null || true
complete -W "--brief" hwcheck hw_check 2>/dev/null || true
complete -W "--share" mksync mkenv 2>/dev/null || true
