#!/bin/bash
# =============================================================================
# scripts/setup_gpu.sh — GPU environment (NVIDIA, Tegra, Intel/AMD, WSL2, CPU).
# Usage: source setup_gpu.sh [auto|nvidia|tegra|igpu|intel|amd|cpu|status|opencv_args]
# Writes ${HOME}/.gpu_env.sh so shells that skip the entrypoint (docker exec,
# make shell/term, VS Code) get the same environment; init_bash.sh sources it.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd 2>/dev/null || echo ".")"
source "${SCRIPT_DIR}/../config/util_paths.sh" 2>/dev/null || true
devkit_require "util_logging.sh"    2>/dev/null || true
devkit_require "util_gpu_detect.sh" 2>/dev/null || true

# Strip colour when piped/redirected or NO_COLOR is set (see util_logging.sh).
# Only for the read-only `status` view: the other modes are sourced into the
# caller's shell, where redirecting its stdout would be a surprising side effect.
[ "${1:-}" = "status" ] && declare -F devkit_auto_color >/dev/null 2>&1 && devkit_auto_color

# Every variable this script owns. Listed once: reset, persist and diagnostics
# all iterate this array, so adding a knob never needs a second edit.
GPU_ENV_VARS=(
    LIBGL_ALWAYS_SOFTWARE LIBGL_ALWAYS_INDIRECT
    MESA_LOADER_DRIVER_OVERRIDE MESA_D3D12_DEFAULT_ADAPTER_NAME GALLIUM_DRIVER
    __NV_PRIME_RENDER_OFFLOAD __GLX_VENDOR_LIBRARY_NAME __VK_LAYER_NV_optimus
    __EGL_VENDOR_LIBRARY_FILENAMES VK_ICD_FILENAMES
    GBM_BACKEND QT_QPA_PLATFORM GDK_BACKEND
    QT_XCB_FORCE_SOFTWARE_OPENGL
)

GPU_ENV_FILE="${GPU_ENV_FILE:-${HOME}/.gpu_env.sh}"

# Directories this script prepends to LD_LIBRARY_PATH. Tracked separately so the
# persisted file can re-prepend exactly these, never a whole-path snapshot.
GPU_LIB_DIRS=()

__gpu_reset()  { unset "${GPU_ENV_VARS[@]}"; }

__gpu_path_prepend() {
    local dir="$1"
    [ -d "$dir" ] || return 0
    case ":${LD_LIBRARY_PATH:-}:" in
        *":$dir:"*) ;;
        *) export LD_LIBRARY_PATH="$dir${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" ;;
    esac
    GPU_LIB_DIRS+=("$dir")
}

# Persist the resolved environment for non-entrypoint shells.
__gpu_persist() {
    local var
    [ -w "$(dirname "$GPU_ENV_FILE")" ] 2>/dev/null || return 0
    {
        echo "# Generated by scripts/setup_gpu.sh — do not edit (regenerate with: gpu <mode>)"
        for var in "${GPU_ENV_VARS[@]}"; do
            [ -n "${!var:-}" ] && printf 'export %s=%q\n' "$var" "${!var}"
        done
        # Prepend, never assign: this is written before ROS is sourced, so a
        # whole-snapshot assignment wipes /opt/ros/<distro>/lib on re-source.
        local dir
        for dir in ${GPU_LIB_DIRS[@]+"${GPU_LIB_DIRS[@]}"}; do
            printf 'case ":${LD_LIBRARY_PATH}:" in *":%s:"*) ;; *) export LD_LIBRARY_PATH="%s${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" ;; esac\n' "$dir" "$dir"
        done
    } > "$GPU_ENV_FILE" 2>/dev/null || true
}

__gpu_nvidia_native() {
    export LIBGL_ALWAYS_SOFTWARE=0
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __VK_LAYER_NV_optimus=NVIDIA_only
    export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json

    if has_dxg 2>/dev/null; then
        # WSL2: CUDA is native but OpenGL always crosses the Mesa D3D12
        # bridge. Without the adapter hint Mesa picks the first adapter — the
        # iGPU on a hybrid laptop — and GL renders on the wrong device.
        export __GLX_VENDOR_LIBRARY_NAME=mesa
        export MESA_LOADER_DRIVER_OVERRIDE=d3d12
        export GALLIUM_DRIVER=d3d12
        export MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
        export LIBGL_ALWAYS_INDIRECT=0
        __gpu_path_prepend "/usr/lib/wsl/lib"
        LOG_PREFIX="[GPU]" log_ok "NVIDIA active — CUDA native, OpenGL via D3D12 bridge (adapter: NVIDIA)"
        return 0
    fi

    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    # Pin the NVIDIA Vulkan ICD when present, or Mesa's ICDs win the loader race
    # and vulkaninfo reports llvmpipe on a perfectly good GPU.
    local icd
    for icd in /usr/share/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json; do
        if [ -f "$icd" ]; then export VK_ICD_FILENAMES="$icd"; break; fi
    done
    # NVIDIA + Wayland needs the vendor GBM backend or EGL apps fall back to
    # software — but only when nvidia-drm KMS is actually modeset (forcing it
    # without makes gbm_create_device fail outright, worse than the fallback).
    if [ -n "${WAYLAND_DISPLAY:-}" ] \
       && [ "$(cat /sys/module/nvidia_drm/parameters/modeset 2>/dev/null)" = "Y" ]; then
        export GBM_BACKEND=nvidia-drm
        export QT_QPA_PLATFORM="wayland;xcb"
        export GDK_BACKEND="wayland,x11"
    fi
    LOG_PREFIX="[GPU]" log_ok "NVIDIA hardware acceleration active (OpenGL + Vulkan + EGL)"
}

# WSL2 renders every vendor through the Mesa D3D12 (Dozen) bridge.
# /usr/lib/wsl/lib holds the host libd3d12/libcuda stubs and MUST be on the
# loader path or GL falls back to llvmpipe.
__gpu_wsl_d3d12() {
    local adapter="${1:-}"
    export LIBGL_ALWAYS_SOFTWARE=0
    export LIBGL_ALWAYS_INDIRECT=0
    export __GLX_VENDOR_LIBRARY_NAME=mesa
    export MESA_LOADER_DRIVER_OVERRIDE=d3d12
    export GALLIUM_DRIVER=d3d12
    [ -z "$adapter" ] && has_nvidia 2>/dev/null && adapter="NVIDIA"
    [ -n "$adapter" ] && export MESA_D3D12_DEFAULT_ADAPTER_NAME="$adapter"
    __gpu_path_prepend "/usr/lib/wsl/lib"
    LOG_PREFIX="[GPU]" log_ok "WSL2 Mesa/D3D12 bridge active${adapter:+ (adapter: ${adapter})}"
}

__gpu_mesa() {
    local driver="$1" label="$2"
    export LIBGL_ALWAYS_SOFTWARE=0
    if [ -n "$driver" ]; then
        export MESA_LOADER_DRIVER_OVERRIDE="$driver"
        export GALLIUM_DRIVER="$driver"
    fi
    LOG_PREFIX="[GPU]" log_ok "${label}"
}

# NVIDIA Jetson / Tegra: the integrated GPU is driven by the vendor L4T stack
# already present in the image; no GLX/Mesa override must be applied or the
# nvgpu path is bypassed and rendering silently falls back to llvmpipe.
__gpu_tegra() {
    export LIBGL_ALWAYS_SOFTWARE=0
    __gpu_path_prepend "/usr/lib/aarch64-linux-gnu/tegra"
    __gpu_path_prepend "/usr/lib/aarch64-linux-gnu/tegra-egl"
    LOG_PREFIX="[GPU]" log_ok "NVIDIA Tegra/Jetson integrated GPU active (L4T stack)"
}

__gpu_software() {
    export LIBGL_ALWAYS_SOFTWARE=1
    export GALLIUM_DRIVER=llvmpipe
    export QT_XCB_FORCE_SOFTWARE_OPENGL=1
    LOG_PREFIX="[GPU]" log_warn "CPU software rendering (llvmpipe)"
    # Apple Silicon / Intel macOS: Docker Desktop runs a Linux VM with no GPU
    # passthrough, so this is a platform ceiling rather than a misconfiguration.
    if [ "${IS_MACOS:-false}" = "true" ] || [ "${DEVKIT_HOST_IS_MACOS:-false}" = "true" ]; then
        log_detail "macOS containers have no Metal/MPS access — this is expected." >&2
        log_detail "For Apple Silicon GPU (MPS), run PyTorch natively on the host." >&2
    fi
}

# CMake flags for source builds of OpenCV: `cmake $(gpu opencv_args) …`.
# auto enables CUDA when nvcc is present: the flag describes the TARGET, so a
# GPU-less builder still produces a CUDA image. -DWITH_CUDA=ON without
# a compiler fails deep inside the OpenCV build. off forces the CPU path.
__opencv_cmake_args() {
    if [ "${OPENCV_CUDA:-auto}" = "off" ] || ! can_build_cuda 2>/dev/null; then
        echo "-DWITH_CUDA=OFF"
        return 0
    fi
    local args="-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON"
    args+=" -DENABLE_FAST_MATH=ON -DCUDA_FAST_MATH=ON -DWITH_CUBLAS=ON"
    # Build for the architectures actually present (+PTX for forward compat):
    # the default arch list compiles every generation and costs hours.
    local caps
    caps="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | sort -u | paste -sd ';' - || true)"
    [ -n "$caps" ] && args+=" -DCUDA_ARCH_BIN=${caps}+PTX"
    echo "$args"
}

__gpu_req_mode="${1:-auto}"

case "$__gpu_req_mode" in
    -h|--help)
        echo "Usage: source setup_gpu.sh [auto|nvidia|tegra|igpu|intel|amd|cpu|status|opencv_args]"
        return 0 2>/dev/null || exit 0
        ;;
    opencv_args)
        __opencv_cmake_args
        return 0 2>/dev/null || exit 0
        ;;
    status)
        __gpu_row()  { printf '    %-14s %s\n' "$1" "$2"; }
        __gpu_var()  { printf '    %-31s %s\n' "$1" "$2"; }
        __gpu_head() { echo -e "\n  \033[1;36m$1\033[0m"; }
        # Load `key=value` probe output into the shell without eval.
        __gpu_load() { local l; while IFS= read -r l; do [ -n "$l" ] && printf -v "__p_${l%%=*}" '%s' "${l#*=}"; done; }

        echo -e "\n  \033[38;2;45;212;191mGPU & Rendering Stack\033[0m"

        # ── Hardware ────────────────────────────────────────────────────────
        __gpu_head "[Hardware]"
        if has_nvidia 2>/dev/null; then
            __gpu_row "NVIDIA" "$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null | head -1 || nvidia-smi -L 2>/dev/null | head -1)"
            __cuda="$(get_cuda_metadata cuda_ver 2>/dev/null || true)"
            __cudnn="$(get_cuda_metadata cudnn_ver 2>/dev/null || true)"
            [ -n "${__cuda:-}"  ] && __gpu_row "CUDA" "$__cuda${__cudnn:+  (cuDNN $__cudnn)}"
        fi
        has_intel_dri 2>/dev/null && __gpu_row "Intel" "DRI vendor 0x8086"
        has_amd_dri   2>/dev/null && __gpu_row "AMD"   "DRI vendor 0x1002/0x1022"
        has_rocm      2>/dev/null && __gpu_row "ROCm"  "runtime present"
        has_tegra     2>/dev/null && __gpu_row "Tegra" "$(list_glob_basenames '/dev/nvhost-*')"
        __drm_drv="$(get_drm_driver 2>/dev/null || true)"
        [ -n "$__drm_drv" ] && __gpu_row "DRM driver" "$__drm_drv"
        __dri_nodes="$(list_glob_basenames '/dev/dri/renderD*' 2>/dev/null || true)"
        __gpu_row "DRI nodes" "${__dri_nodes:-none}"
        if has_dxg 2>/dev/null; then
            # printf, not echo: bash's echo leaves \033 literal, and the missing
            # host library mount is exactly the line that must stand out.
            __gpu_row "WSL2 D3D12" "/dev/dxg present$([ -d /usr/lib/wsl/lib ] \
                && printf '  (/usr/lib/wsl/lib mounted)' \
                || printf '  \033[33m(/usr/lib/wsl/lib MISSING)\033[0m')"
        fi
        [ -z "${__dri_nodes:-}" ] && ! has_nvidia 2>/dev/null && ! has_dxg 2>/dev/null \
            && echo -e "    \033[33mNo GPU device nodes — software rendering only.\033[0m"

        # ── Display ─────────────────────────────────────────────────────────
        __gpu_head "[Display]"
        if [ -n "${DISPLAY:-}" ]; then
            __x_num="${DISPLAY#:}"; __x_num="${__x_num%%.*}"
            __gpu_row "X11" "DISPLAY=${DISPLAY}  socket=$([ -S "/tmp/.X11-unix/X${__x_num}" ] && echo ok || echo MISSING)"
            __xa="${XAUTHORITY:-$HOME/.Xauthority}"
            __gpu_row "Xauthority" "${__xa}  $([ -s "$__xa" ] && echo ok || echo 'empty/missing → run: make xauth')"
        else
            __gpu_row "X11" "DISPLAY not set"
        fi
        if [ -n "${WAYLAND_DISPLAY:-}" ]; then
            __gpu_row "Wayland" "${WAYLAND_DISPLAY}  socket=$([ -S "${XDG_RUNTIME_DIR:-}/${WAYLAND_DISPLAY}" ] && echo ok || echo MISSING)"
        fi
        __gpu_row "XDG runtime" "${XDG_RUNTIME_DIR:-not set}"

        # ── OpenGL / GLX ────────────────────────────────────────────────────
        __gpu_head "[OpenGL / GLX]"
        __gpu_load < <(probe_gl)
        if [ -n "${__p_gl_renderer:-}" ]; then
            case "$(printf '%s' "$__p_gl_renderer" | tr '[:upper:]' '[:lower:]')" in
                *llvmpipe*|*softpipe*|*swrast*)
                    __gpu_row "renderer" "$(printf '\033[33m%s  (SOFTWARE rendering)\033[0m' "$__p_gl_renderer")" ;;
                *)  __gpu_row "renderer" "$(printf '\033[32m%s\033[0m' "$__p_gl_renderer")" ;;
            esac
            __gpu_row "vendor"   "${__p_gl_vendor:-?}"
            __gpu_row "version"  "${__p_gl_version:-?}"
            __gpu_row "mesa"     "${__p_gl_mesa:-n/a}"
            __gpu_row "direct"   "${__p_gl_direct:-?}   accelerated: ${__p_gl_accelerated:-?}   VRAM: ${__p_gl_vram:-?}"
        elif command -v glxinfo >/dev/null 2>&1; then
            __gpu_row "glxinfo" "no output (DISPLAY unreachable? check xhost / make xauth)"
        else
            __gpu_row "glxinfo" "not installed (apt: mesa-utils)"
        fi

        # ── EGL ─────────────────────────────────────────────────────────────
        __gpu_head "[EGL]"
        __gpu_load < <(probe_egl)
        if [ -n "${__p_egl_vendor:-}" ]; then
            __gpu_row "vendor"   "${__p_egl_vendor}  (EGL ${__p_egl_version:-?})"
            __gpu_row "renderer" "${__p_egl_renderer:-?}"
            __gpu_row "APIs"     "${__p_egl_apis:-?}"
        else
            __gpu_row "eglinfo" "$(command -v eglinfo >/dev/null 2>&1 && echo 'no usable platform (headless?)' || echo 'not installed (apt: mesa-utils)')"
        fi

        # ── Vulkan ──────────────────────────────────────────────────────────
        __gpu_head "[Vulkan]"
        __gpu_load < <(probe_vulkan)
        if [ -n "${__p_vk_device:-}" ]; then
            __gpu_row "device" "${__p_vk_device}  (${__p_vk_type:-?})"
            __gpu_row "API"    "${__p_vk_api:-?}   driver: ${__p_vk_driver:-?}"
        else
            __gpu_row "vulkaninfo" "$(command -v vulkaninfo >/dev/null 2>&1 && echo 'no device (missing ICD? check mesa-vulkan-drivers / nvidia ICD)' || echo 'not installed (apt: vulkan-tools)')"
        fi

        # ── Loader / libraries ──────────────────────────────────────────────
        __gpu_head "[Loader]"
        __libs="$(probe_gl_libs 2>/dev/null || true)"
        if [ -n "$__libs" ]; then
            while IFS='=' read -r __n __pth; do [ -n "$__n" ] && __gpu_row "$__n" "$__pth"; done <<< "$__libs"
        else
            __gpu_row "ldconfig" "unavailable"
        fi

        # ── Active configuration ────────────────────────────────────────────
        __gpu_head "[Active configuration]"
        __gpu_row "GPU_MODE" "${GPU_MODE:-auto}"
        __gpu_row "OPENCV_CUDA" "${OPENCV_CUDA:-auto}  →  $(__opencv_cmake_args)"
        for __v in "${GPU_ENV_VARS[@]}"; do
            [ -n "${!__v:-}" ] && __gpu_var "$__v" "${!__v}"
        done
        [ -n "${LD_LIBRARY_PATH:-}" ] && __gpu_row "LD_LIBRARY_PATH" "$LD_LIBRARY_PATH"
        __gpu_row "persisted" "${GPU_ENV_FILE}$([ -f "$GPU_ENV_FILE" ] && echo '  (ok)' || echo '  (not written — run: gpu auto)')"
        echo ""
        return 0 2>/dev/null || exit 0
        ;;
esac

# Validated before anything is unset: this file is SOURCED, so a typo'd mode
# must not leave the caller's shell stripped of its GPU variables.
case "$__gpu_req_mode" in
    auto|nvidia|tegra|intel|amd|igpu|cpu) ;;
    *)  LOG_PREFIX="[GPU]" log_error "Unknown mode '${__gpu_req_mode}' (valid: auto nvidia tegra intel amd igpu cpu)."
        # `return` when sourced (the `gpu` helper), `exit` when executed.
        return 2 2>/dev/null || exit 2 ;;
esac

__gpu_reset

# Resolve 'auto', most specific first: a discrete NVIDIA device node, then a
# Jetson (which has /dev/nvhost-* and an nvgpu DRI node but no /dev/nvidiactl),
# then ROCm, then the DRI vendors, then WSL's D3D12 node.
if [ "$__gpu_req_mode" = "auto" ]; then
    if has_nvidia 2>/dev/null;      then __gpu_req_mode="nvidia"
    elif has_tegra 2>/dev/null;     then __gpu_req_mode="tegra"
    elif has_rocm 2>/dev/null;      then __gpu_req_mode="amd"
    elif has_intel_dri 2>/dev/null; then __gpu_req_mode="intel"
    elif has_amd_dri 2>/dev/null;   then __gpu_req_mode="amd"
    elif has_dxg 2>/dev/null;       then __gpu_req_mode="igpu"
    # SoC GPUs (Mali, Adreno, VideoCore, Vivante) are platform devices with no
    # PCI vendor id, so the probes above miss them. If a render node exists, let
    # Mesa choose — forcing llvmpipe would waste a working GPU.
    elif has_any_dri 2>/dev/null;   then __gpu_req_mode="igpu"
    else                                 __gpu_req_mode="cpu"
    fi
fi


if [ "$__gpu_req_mode" = "cpu" ]; then
    __gpu_software
elif has_dxg 2>/dev/null && ! { [ "$__gpu_req_mode" = "nvidia" ] && [ "${HAS_TOOLKIT:-false}" = "true" ]; }; then
    # WSL2: everything but a toolkit-backed NVIDIA runtime goes through D3D12.
    case "$__gpu_req_mode" in
        nvidia) __gpu_wsl_d3d12 "NVIDIA" ;;
        intel)  __gpu_wsl_d3d12 "Intel"  ;;
        amd)    __gpu_wsl_d3d12 "AMD"    ;;
        *)      __gpu_wsl_d3d12 ""       ;;
    esac
else
    case "$__gpu_req_mode" in
        nvidia) __gpu_nvidia_native ;;
        tegra)  __gpu_tegra ;;
        intel)  if [ -d /sys/module/xe ]; then __gpu_mesa ""      "Intel GPU active (xe driver)"
                else                           __gpu_mesa "iris"  "Intel GPU active (Mesa/iris)"; fi ;;
        amd)    __gpu_mesa "radeonsi" "AMD GPU active (Mesa/radeonsi)" ;;
        igpu)   __gpu_mesa ""         "Integrated/SoC GPU active via Mesa$(d=$(get_drm_driver 2>/dev/null || true); [ -n "$d" ] && echo " (DRM driver: $d)")" ;;
    esac
fi

__gpu_persist
